import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeSwitch from "@/components/ThemeSwitch";
import Link from "next/link";
import { House } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <div className="container flex items-center mx-auto mt-5 mb-10">
            <Link href="/" className="p-2 hover:bg-foreground/5 rounded">
              <House size={24} />
            </Link>
            <ThemeSwitch className="inline-block ml-auto"></ThemeSwitch>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
